[package]
name = "libmpv-client-sys"
version = "0.2.0"
readme.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
build = "build.rs"

[features]
dyn-sym = []

[dependencies]
paste = "1.0.15"

[build-dependencies]
bindgen = "0.71.1"